#we are searching for these things, and then replacing them with itself for use in the dictionary
change = ["Amazon.com",
          "AMZN Mktp",
          "GUSTO",
          "RITA S CATERING",
          "T-MOBILE",
          "MARKET BASKET",
          "STP&SHPFUEL",
          "5GUYS",
          "A L PRIME BEVERLY",
          "AMERICAN PETROLEUM",
          "Audible",
          "DUNKIN",
          "KIKI",
          "MCDONALD",
          "AMAZON.COM",
          "TARGET",
          "ATM Withdrawal - SALEM FIVE BANK",
          "PAPAGINOS",
          "BJS WHOLESALE",
          "AMZNFreeTime",
          "COMCAST",
          "MEDITECH PAYROLL",
          "PNC MORTGAGE",
          "GreenSky",
          "SUNOCO",
          "Prime Video",
          "M&M ENERGY LLC",
          "Market Basket",
          "Amazon.ca",
          "Wal-Mart Store",
          "GULF",
          "BLUE HILL EXPRE",
          "Preauthorized Credit",
          "SHAWS",
          "ATM Deposit",
          "TACO BELL",
          "PUTNAM PANTRY",
          "PANERA BREAD",
          "PETE'S A PLACE",
          "SHOP 0005 PEABODY",
          "MA DUA MASS UNEMPLOYMENT DD",
          "PEPPYS PIZZA INC SALEM MAUS",
          "DOMINO",
          "SIAM DELIGHT",
"BEVERLY MOBIL"
          ]
